### ISSUE TITLE
Doubt about the circuit

### ISSUE THREAD

**Issue by d-solis-tovar** [danielkucera/ebus-adapter#10]
Hi Daniel,

I would like to implement ebus protocol to an existing circuit with esp32 (so I just need the part from UART at ESP32 to EBUS terminal). As I understand from your wiring schematics, I would need to implement just this part of the circuit, right?

![screenshot](https://github.com/danielkucera/ebus-adapter/assets/131579931/4ef2c8cc-6510-4215-b5b1-7590d41d2650)

Thank you in advance!

**Comment by danielkucera** [comment]
yes
