### ISSUE TITLE
User manual and some suggestions for improvement

### ISSUE THREAD

**Issue by bogdanm** [danielkucera/ebus-adapter#4]
Hi, I recently bought your adapter from Lectronz, then I realized that I don't actually know what I'm supposed to do with the trimmer. Is there an user manual somewhere?
Staying in the area of general usability, is there a PDF schematic somewhere, or another format that's easy to read? I don't use KiCad and I wouldn't want to install it just to be able to read the schematic.
Thank you.

**Comment by danielkucera** [comment]
Hi,
sorry for not providing any details.
Trimmer should be configured to work correctly but if you don't see any data from your bus, you can try adjusting it.

Schematics can be found in releases as described in readme or you can see the project on cadlab.io, see the first line in readme.

Thanks.

**Comment by bogdanm** [comment]
Thank you! Also, my bad, I completely missed the cadlab link.

**Comment by danielkucera** [comment]
I just added today :)
