### ISSUE TITLE
Compatible with Vaillant eBus ?

### ISSUE THREAD

**Issue by HiQual** [danielkucera/ebus-adapter#6]
Hello.
Before buying your adapter, I just want to check that it is fully compatible with Vaillant eBus ?
Also, is it 2 way - with suitable software can I send instructions to the Vaillant boiler - example, increase flow temperature ?
Many thanks.

**Comment by danielkucera** [comment]
Hi, I was using it with vaillant ecotec pro for several years. And yes, you can also send frames with it.

**Comment by HiQual** [comment]
Thank you for your answer.  I now want to buy one.  The shop is out of stock at the moment.  Do you have any plans to make the next batch?  If not, do you have any prototype boards you would be willing to sell ?
I will be using your board with an excellent application called MaxAir  (github.com/pihome-shc/PiHomeHVAC) which has just integrated eBus communication so I will be sharing my experiences of your adapter on their discussion groups.

**Comment by danielkucera** [comment]
I have just completed 6 boards. They need to be tested and after testing they will go to sale.

**Comment by HiQual** [comment]
Thanks for the update.
